### ISSUE TITLE
bug: null values in propertoes

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pv-forecast-blend#18] opened 2023-10-24 16:15 UTC
## Detailed Description
Work out and try to fix why the properties blend ended up being 
![Screenshot 2023-10-24 at 17 14 02](https://github.com/openclimatefix/uk-pv-forecast-blend/assets/34686298/72272bd2-6b41-4894-b23a-1d8611edba14)
![Screenshot 2023-10-24 at 17 13 48](https://github.com/openclimatefix/uk-pv-forecast-blend/assets/34686298/55111b79-6550-46aa-af28-e42ebabb87d3)

## Context
- airflow was out of memory so the forecast may have not run
- target_time='2023-10-24 23:30:00+00'
- This error actually happened in the API, but was made by the blend service

## Possible Implementation
if Null, make properties an empty dict

**Comment by aryanbhosale** [comment] 2024-04-19 16:17
Hi @peterdudfield , it seems that the issue is related to the properties column in the blended_df DataFrame being None. The properties column is expected to be a dictionary containing the 10 and 90 percentile values for the forecast, am i right?

**Comment by aryanbhosale** [comment] 2024-04-24 09:50
Hi @peterdudfield ,can we close this?

**Closed as completed** 2024-04-24 10:51 UTC
